apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-with-envoy
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      # 3 conteneurs dans le même Pod
      containers:
        - name: go-app
          image: xpdemon/go-server:latest
        - name: envoy
          image: xpdemon/envoy-proxy:latest
          ports:
            - containerPort: 80
        - name: ext-authz
          image: xpdemon/go-auth:latest