apiVersion: apps/v1
kind: Deployment
metadata:
  name: ext-authz
  labels:
    app: ext-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ext-authz
  template:
    metadata:
      labels:
        app: ext-authz
    spec:
      containers:
        - name: ext-authz
          image: xpdemon/go-auth:latest
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: ext-authz
  labels:
    app: ext-authz
spec:
  selector:
    app: ext-authz
  ports:
    - name: http
      port: 9000
      targetPort: 9000